### ISSUE TITLE
Facebook and Twitter sign up/in

### ISSUE THREAD

**Issue by yuchan** [SocioQuiz/socio_quiz#1]
## Implement Facebook and Twitter sign up/in.
- use devise and omnioauth
- register app for tw/fb
- create sign up view
- prepare user model

**Comment by not001praween001** [comment]
Here we think that it should to be let Khánh creates both tw/fb account (or using his account) to generate the App for cooperating with Login feature of our SocioQuiz.
(May be discuss the next meeting or recently here or Facebook chat)

**Comment by yuchan** [comment]
SIgn up/in implementation was already done.
