### ISSUE TITLE
Need to update stack at dyno

### ISSUE THREAD

**Issue by not001praween001** [SocioQuiz/socio_quiz#45]
Memo Link [here](https://devcenter.heroku.com/articles/cedar-14-migration)
Assign: yuchan

**Comment by yuchan** [comment]
I did at #44.

**Comment by yuchan** [comment]
But Travis error isn't fixed yet.

**Comment by not001praween001** [comment]
Cloud we have to update it at HEROKU product dyno?

**Comment by yuchan** [comment]
fixed.
